import React, { useState } from 'react';
import { Alert, Incident } from '../types';
import { ThreatBadge } from '../components/common/ThreatBadge';
import {
  AlertTriangle,
  CheckCircle2,
  ChevronRight,
  Bot,
  Filter,
  ArrowUpRight,
  Clock,
  ShieldAlert,
  Flame
} from 'lucide-react';

interface AlertsPageProps {
  alerts: Alert[];
  incidents: Incident[];
  onAcknowledge: (id: number) => void;
  onViewIncident: (inc: Incident) => void;
  onOpenAssistantWithIncident: (code: string) => void;
}

export const AlertsPage: React.FC<AlertsPageProps> = ({
  alerts,
  incidents,
  onAcknowledge,
  onViewIncident,
  onOpenAssistantWithIncident
}) => {
  const [filterSeverity, setFilterSeverity] = useState<string>('ALL');
  const [filterAck, setFilterAck] = useState<'ALL' | 'UNACK' | 'ACK'>('ALL');

  const filteredAlerts = alerts.filter((a) => {
    if (filterSeverity !== 'ALL' && a.severity !== filterSeverity) return false;
    if (filterAck === 'UNACK' && a.acknowledged) return false;
    if (filterAck === 'ACK' && !a.acknowledged) return false;
    return true;
  });

  const getIncidentForAlert = (alert: Alert): Incident | undefined => {
    return incidents.find((i) => i.id === alert.incident_id);
  };

  return (
    <div className="p-6 space-y-6 max-w-[1500px] mx-auto animate-in fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-mono font-bold tracking-wide text-slate-100">
              Perimeter Alert Center
            </h1>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-red-950 text-red-400 border border-red-800 font-semibold">
              {alerts.filter((a) => !a.acknowledged).length} UNACKNOWLEDGED
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Real-time security notifications generated by the Threat Scoring Engine
          </p>
        </div>

        {/* Filters */}
        <div className="flex items-center gap-3 font-mono text-xs flex-wrap">
          <div className="flex items-center gap-1 bg-[#0B0F17] p-1 rounded-lg border border-slate-800">
            {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW'].map((sev) => (
              <button
                key={sev}
                onClick={() => setFilterSeverity(sev)}
                className={`px-2.5 py-1 rounded transition-colors ${
                  filterSeverity === sev
                    ? 'bg-slate-700 text-white font-bold'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {sev}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-1 bg-[#0B0F17] p-1 rounded-lg border border-slate-800">
            <button
              onClick={() => setFilterAck('ALL')}
              className={`px-2.5 py-1 rounded ${filterAck === 'ALL' ? 'bg-cyan-950 text-cyan-300 font-bold border border-cyan-700/60' : 'text-slate-400'}`}
            >
              ALL
            </button>
            <button
              onClick={() => setFilterAck('UNACK')}
              className={`px-2.5 py-1 rounded ${filterAck === 'UNACK' ? 'bg-red-950 text-red-300 font-bold border border-red-700/60' : 'text-slate-400'}`}
            >
              ACTIVE ONLY
            </button>
            <button
              onClick={() => setFilterAck('ACK')}
              className={`px-2.5 py-1 rounded ${filterAck === 'ACK' ? 'bg-emerald-950 text-emerald-300 font-bold border border-emerald-700/60' : 'text-slate-400'}`}
            >
              ACKNOWLEDGED
            </button>
          </div>
        </div>
      </div>

      {/* Alerts Stream */}
      <div className="space-y-3">
        {filteredAlerts.length === 0 ? (
          <div className="text-center py-12 text-slate-500 font-mono text-xs">
            No alerts match the selected criteria.
          </div>
        ) : (
          filteredAlerts.map((alert) => {
            const inc = getIncidentForAlert(alert);
            const isCrit = alert.severity === 'CRITICAL';

            return (
              <div
                key={alert.id}
                className={`bg-[#0B0F17] border rounded-xl p-4 transition-all flex flex-col md:flex-row md:items-center justify-between gap-4 font-mono text-xs ${
                  !alert.acknowledged && isCrit
                    ? 'border-red-600/70 bg-red-950/10 shadow-lg shadow-red-950/20'
                    : !alert.acknowledged
                    ? 'border-slate-700'
                    : 'border-slate-850 opacity-75'
                }`}
              >
                <div className="flex items-start gap-3.5">
                  <div
                    className={`w-9 h-9 rounded-lg flex items-center justify-center shrink-0 border ${
                      isCrit
                        ? 'bg-red-500/20 text-red-400 border-red-500/40'
                        : 'bg-amber-500/20 text-amber-400 border-amber-500/40'
                    }`}
                  >
                    <AlertTriangle className="w-5 h-5" />
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <ThreatBadge severity={alert.severity} />
                      <span className="font-bold text-slate-100 text-sm">{alert.message}</span>
                      {alert.acknowledged && (
                        <span className="px-2 py-0.5 rounded bg-emerald-950 text-emerald-400 border border-emerald-800 text-[10px]">
                          ✓ ACKNOWLEDGED BY {alert.acknowledged_by || 'COMMAND'}
                        </span>
                      )}
                    </div>

                    <div className="text-[11px] text-slate-400 flex items-center gap-3">
                      <span>TIME: <strong className="text-slate-300">{new Date(alert.created_at).toLocaleTimeString()}</strong></span>
                      <span>•</span>
                      <span>INCIDENT: <strong className="text-cyan-400">{inc?.incident_code || 'N/A'}</strong></span>
                      <span>•</span>
                      <span>SECTOR: <strong className="text-slate-300">{inc?.sector || 'Sector B'}</strong></span>
                    </div>
                  </div>
                </div>

                {/* Right Action Buttons */}
                <div className="flex items-center gap-2 shrink-0 flex-wrap">
                  {inc && (
                    <button
                      onClick={() => onViewIncident(inc)}
                      className="px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 flex items-center gap-1 transition-colors"
                    >
                      <span>VIEW INCIDENT</span>
                      <ChevronRight className="w-3.5 h-3.5" />
                    </button>
                  )}

                  {inc && (
                    <button
                      onClick={() => onOpenAssistantWithIncident(inc.incident_code)}
                      className="px-3 py-1.5 rounded bg-cyan-950/80 hover:bg-cyan-900 text-cyan-300 border border-cyan-700/60 flex items-center gap-1 transition-colors"
                    >
                      <Bot className="w-3.5 h-3.5 text-cyan-400" />
                      <span>OPEN AI ASSISTANT</span>
                    </button>
                  )}

                  {!alert.acknowledged && (
                    <button
                      onClick={() => onAcknowledge(alert.id)}
                      className="px-3 py-1.5 rounded bg-emerald-950/80 hover:bg-emerald-900 text-emerald-300 border border-emerald-700/60 flex items-center gap-1 transition-colors font-semibold"
                    >
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      <span>ACKNOWLEDGE</span>
                    </button>
                  )}
                </div>
              </div>
            );
          })
        )}
      </div>
    </div>
  );
};
