import React, { useState } from 'react';
import { EvidenceRecord, Incident } from '../types';
import { ThreatBadge } from '../components/common/ThreatBadge';
import {
  FolderArchive,
  FileImage,
  Video,
  ExternalLink,
  ShieldCheck,
  Search,
  Filter,
  Download,
  Eye,
  Camera as CameraIcon,
  Flame,
  CheckCircle2
} from 'lucide-react';

interface EvidenceVaultPageProps {
  evidenceList: EvidenceRecord[];
  incidents: Incident[];
  onSelectIncident: (inc: Incident) => void;
}

export const EvidenceVaultPage: React.FC<EvidenceVaultPageProps> = ({
  evidenceList,
  incidents,
  onSelectIncident
}) => {
  const [activeCategory, setActiveCategory] = useState<string>('All');
  const [inspectEvidence, setInspectEvidence] = useState<EvidenceRecord | null>(null);

  const categories = [
    'All',
    'Intrusion',
    'Boundary Crossing',
    'Vehicle',
    'Abandoned Object',
    'Unusual Movement',
    'Critical'
  ];

  const getIncidentForEvidence = (ev: EvidenceRecord): Incident | undefined => {
    return incidents.find((i) => i.id === ev.incident_id);
  };

  const filtered = evidenceList.filter((ev) => {
    const inc = getIncidentForEvidence(ev);
    if (!inc) return true;
    if (activeCategory === 'All') return true;
    if (activeCategory === 'Critical') return inc.severity === 'CRITICAL';
    if (activeCategory === 'Intrusion') return inc.incident_type.toLowerCase().includes('intrusion');
    if (activeCategory === 'Boundary Crossing') return inc.incident_type.toLowerCase().includes('boundary') || inc.threat_factors.some(f => f.toLowerCase().includes('boundary'));
    if (activeCategory === 'Vehicle') return ev.object_type === 'VEHICLE' || inc.incident_type.toLowerCase().includes('vehicle');
    if (activeCategory === 'Abandoned Object') return ev.object_type.includes('ABANDONED') || inc.incident_type.toLowerCase().includes('abandoned');
    if (activeCategory === 'Unusual Movement') return inc.incident_type.toLowerCase().includes('movement');
    return true;
  });

  return (
    <div className="p-6 space-y-6 max-w-[1600px] mx-auto animate-in fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-xl font-mono font-bold tracking-wide text-slate-100">
              Forensic Evidence Vault
            </h1>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-800 font-semibold flex items-center gap-1">
              <ShieldCheck className="w-3 h-3 text-purple-400" />
              <span>SHA-256 IMMUTABLE STORE</span>
            </span>
          </div>
          <p className="text-xs text-slate-400 mt-0.5">
            Cryptographically logged snapshots, bounding coordinates, and video loops generated by Threat Engine
          </p>
        </div>

        {/* Category Filters */}
        <div className="flex items-center gap-1.5 bg-[#0B0F17] p-1 rounded-lg border border-slate-800 font-mono text-xs flex-wrap">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1 rounded transition-colors ${
                activeCategory === cat
                  ? 'bg-purple-900/60 text-purple-200 font-bold border border-purple-700/60'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Evidence Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 font-mono text-xs">
        {filtered.map((ev) => {
          const inc = getIncidentForEvidence(ev);

          return (
            <div
              key={ev.id}
              className="bg-[#0B0F17] rounded-xl border border-slate-800 hover:border-slate-700 transition-all overflow-hidden flex flex-col group shadow-xl"
            >
              {/* Synthetic Snapshot Thumbnail */}
              <div className="relative aspect-video bg-[#06090F] flex items-center justify-center border-b border-slate-800 overflow-hidden">
                {/* Simulated CCTV Evidence Graphic */}
                <div className="w-full h-full bg-gradient-to-b from-[#0F172A] to-[#020617] p-3 flex flex-col justify-between relative">
                  <div className="flex items-center justify-between text-[10px] text-cyan-400 z-10">
                    <span className="bg-black/70 px-1.5 py-0.5 rounded font-bold">
                      {inc?.camera_id || 'C-07'} • {ev.object_type}
                    </span>
                    <span className="text-slate-400">{new Date(ev.timestamp).toLocaleTimeString()}</span>
                  </div>

                  {/* Simulated bounding box frame */}
                  <div className="absolute inset-8 border border-red-500/70 bg-red-500/10 rounded flex flex-col justify-between p-1">
                    <span className="text-[9px] text-red-400 font-bold bg-black/80 px-1 rounded self-start">
                      {ev.object_type} {ev.track_id} ({(ev.confidence * 100).toFixed(1)}%)
                    </span>
                    <span className="text-[8px] text-cyan-300 bg-black/80 px-1 rounded self-end">
                      RISK {inc?.risk_score || 87}/100
                    </span>
                  </div>

                  <div className="flex items-center justify-between text-[9px] text-slate-500 z-10">
                    <span>EVIDENCE #{ev.id}</span>
                    <span className="text-emerald-400">VERIFIED AI FORENSIC</span>
                  </div>
                </div>

                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                  <button
                    onClick={() => setInspectEvidence(ev)}
                    className="p-2 rounded bg-cyan-600 text-white shadow-lg hover:bg-cyan-500"
                    title="Inspect Forensic Metadata"
                  >
                    <Eye className="w-4 h-4" />
                  </button>
                  {inc && (
                    <button
                      onClick={() => onSelectIncident(inc)}
                      className="p-2 rounded bg-slate-800 text-slate-200 shadow-lg hover:bg-slate-700"
                      title="Open Associated Incident"
                    >
                      <ExternalLink className="w-4 h-4" />
                    </button>
                  )}
                </div>
              </div>

              {/* Card Body */}
              <div className="p-4 space-y-3 flex-1 flex flex-col justify-between">
                <div>
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-200 text-sm">{inc?.incident_code}</span>
                    {inc && <ThreatBadge severity={inc.severity} />}
                  </div>
                  <div className="text-slate-300 font-sans font-medium text-xs mt-1">
                    {inc?.incident_type}
                  </div>
                </div>

                <div className="space-y-1.5 pt-2 border-t border-slate-850 text-[11px] text-slate-400">
                  <div className="flex items-center justify-between">
                    <span>TRACK ID:</span>
                    <span className="text-cyan-400 font-bold">{ev.track_id}</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>CONFIDENCE:</span>
                    <span className="text-emerald-400">{(ev.confidence * 100).toFixed(1)}%</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span>SECTOR:</span>
                    <span className="text-slate-300">{inc?.sector}</span>
                  </div>
                </div>

                <div className="pt-2 flex items-center justify-between gap-2">
                  <button
                    onClick={() => setInspectEvidence(ev)}
                    className="flex-1 py-1.5 rounded bg-slate-900 hover:bg-slate-800 text-slate-300 border border-slate-700 flex items-center justify-center gap-1.5 transition-colors text-[11px]"
                  >
                    <FileImage className="w-3.5 h-3.5 text-cyan-400" />
                    <span>INSPECT</span>
                  </button>
                  {inc && (
                    <button
                      onClick={() => onSelectIncident(inc)}
                      className="flex-1 py-1.5 rounded bg-purple-950/80 hover:bg-purple-900 text-purple-300 border border-purple-800/60 flex items-center justify-center gap-1.5 transition-colors text-[11px]"
                    >
                      <Video className="w-3.5 h-3.5 text-purple-400" />
                      <span>TIMELINE</span>
                    </button>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Forensic Inspection Modal */}
      {inspectEvidence && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in">
          <div className="bg-[#0B0F17] border border-slate-700 rounded-xl max-w-2xl w-full p-6 space-y-4 font-mono text-xs shadow-2xl">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2">
                <FolderArchive className="w-4 h-4 text-purple-400" />
                <h3 className="font-bold text-sm text-slate-100">
                  Forensic Proof Dossier #{inspectEvidence.id}
                </h3>
              </div>
              <button
                onClick={() => setInspectEvidence(null)}
                className="text-slate-400 hover:text-slate-200"
              >
                ✕
              </button>
            </div>

            <div className="aspect-video bg-black rounded-lg border border-slate-800 flex items-center justify-center relative overflow-hidden">
              <div className="absolute top-3 left-3 text-cyan-400 font-bold">
                ENCRYPTED PROOF SNAPSHOT
              </div>
              <div className="border border-red-500/80 p-4 bg-red-950/20 text-center">
                <div className="text-red-400 font-bold text-sm">
                  {inspectEvidence.object_type} {inspectEvidence.track_id}
                </div>
                <div className="text-slate-400 text-[11px] mt-1">
                  Confidence: {(inspectEvidence.confidence * 100).toFixed(1)}% • 1080p FHD
                </div>
              </div>
            </div>

            <div className="bg-[#070A0F] p-3 rounded-lg border border-slate-800 space-y-2 text-[11px]">
              <div className="flex items-center justify-between text-slate-400">
                <span>CRYPTO SHA-256 HASH:</span>
                <span className="text-slate-200">8f4a1c2b5e9d3a7764f2010c926a4b11f3d8a9e201bcf4d1a0e8c71b3e945c22</span>
              </div>
              <div className="flex items-center justify-between text-slate-400">
                <span>CAPTURE TIMESTAMP:</span>
                <span className="text-slate-200">{inspectEvidence.timestamp}</span>
              </div>
              <div className="flex items-center justify-between text-slate-400">
                <span>STORAGE VAULT:</span>
                <span className="text-emerald-400">LOCAL_FORENSIC_SECURE_VAULT / AWS S3 COMPATIBLE</span>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-800">
              <button
                onClick={() => setInspectEvidence(null)}
                className="px-4 py-1.5 rounded bg-slate-800 text-slate-200 hover:bg-slate-700"
              >
                CLOSE
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
